import { Document, Page, Text, View, StyleSheet, PDFDownloadLink } from '@react-pdf/renderer';
import type { PrescriptionRecord } from '../../../lib/types';

const styles = StyleSheet.create({
  page: {
    padding: 32,
    fontSize: 11,
    color: '#0f172a',
    fontFamily: 'Helvetica',
  },
  header: {
    borderBottom: 1,
    borderBottomColor: '#cbd5e1',
    paddingBottom: 12,
    marginBottom: 20,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1e40af',
  },
  subtitle: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 2,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  infoLabel: {
    color: '#64748b',
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    marginTop: 16,
    marginBottom: 8,
  },
  medCard: {
    border: 1,
    borderColor: '#e2e8f0',
    borderRadius: 4,
    padding: 10,
    marginBottom: 8,
  },
  medName: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  medLine: {
    marginTop: 4,
    color: '#334155',
  },
  notes: {
    marginTop: 16,
    color: '#334155',
    lineHeight: 1.4,
  },
  footer: {
    position: 'absolute',
    bottom: 32,
    left: 32,
    right: 32,
    borderTop: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 8,
    fontSize: 9,
    color: '#94a3b8',
  },
});

export interface PrescriptionPdfProps {
  prescription: PrescriptionRecord;
  patientName: string;
  patientMrn: string;
  doctorName: string;
  tokenNumber: number;
}

export function PrescriptionPDF({
  prescription,
  patientName,
  patientMrn,
  doctorName,
  tokenNumber,
}: PrescriptionPdfProps) {
  const date = new Date(prescription.createdAt);
  const dateText = isNaN(date.getTime())
    ? ''
    : date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });

  return (
    <Document>
      <Page size="A5" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Clinic Management System</Text>
          <Text style={styles.subtitle}>Medical Prescription</Text>
        </View>

        <View style={styles.infoRow}>
          <Text>
            <Text style={styles.infoLabel}>Patient: </Text>
            {patientName}
          </Text>
          <Text>
            <Text style={styles.infoLabel}>Token: </Text>#{tokenNumber}
          </Text>
        </View>
        <View style={styles.infoRow}>
          <Text>
            <Text style={styles.infoLabel}>MRN: </Text>
            {patientMrn}
          </Text>
          <Text>{dateText}</Text>
        </View>
        <View style={styles.infoRow}>
          <Text>
            <Text style={styles.infoLabel}>Doctor: </Text>
            {doctorName}
          </Text>
        </View>

        <Text style={styles.sectionTitle}>Medications</Text>
        {prescription.medications.map((med, index) => (
          <View key={index} style={styles.medCard}>
            <Text style={styles.medName}>
              {index + 1}. {med.name}
              {med.dosage ? ` — ${med.dosage}` : ''}
            </Text>
            {med.frequency || med.duration ? (
              <Text style={styles.medLine}>
                {med.frequency}
                {med.frequency && med.duration ? ' · ' : ''}
                {med.duration}
              </Text>
            ) : null}
            {med.instructions ? <Text style={styles.medLine}>{med.instructions}</Text> : null}
          </View>
        ))}

        {prescription.notes ? <Text style={styles.notes}>Notes: {prescription.notes}</Text> : null}

        <Text style={styles.footer}>
          Generated by Clinic Management System · {new Date().toLocaleString('en-GB')}
        </Text>
      </Page>
    </Document>
  );
}

export function PrescriptionDownload({ ...props }: PrescriptionPdfProps) {
  return (
    <PDFDownloadLink
      document={<PrescriptionPDF {...props} />}
      fileName={`prescription-${props.tokenNumber}-${props.patientMrn}.pdf`}
      className="inline-flex items-center justify-center rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-blue-700"
    >
      {({ loading }) => (loading ? 'Preparing…' : 'Download PDF')}
    </PDFDownloadLink>
  );
}
